#!/usr/bin/env python3
"""Generate the paper from the JSON written by 01 to 06. No figure is typed by hand.

Structure follows Breton, Shields and Kovatchev, J Diabetes Sci Technol 2008;2(3):495-500:
structured abstract, introduction, methods with the mathematical apparatus and a data
subsection last, results, discussion, abbreviations, references. Numbered display equations.
Numerical findings sit in prose where they can, with tables reserved for genuinely tabular
material. House style is checked by 09_style_check.py.
"""
import sys, os, textwrap
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cadence_lib as L

P  = L.read("01_profile.json"); V  = L.read("02_variogram.json")
F  = L.read("03_forecast.json"); Ev = L.read("04_events.json")
Dl = L.read("05_reporting_delay.json"); Ac = L.read("06_acceleration.json"); Mc = L.read("07_meal_climbs.json")
rs = V["ratio_summary"]; cp = P["comparability"]; sd_ = Ac["scale_dependence"]
s5 = V["slopes"]["e5"]; s1 = V["slopes"]["e1"]
out = []; w = out.append

w("# Sampling rate and information content in continuous glucose monitoring: "
  "a within-subject comparison of one-minute and five-minute sensors")
w("")
w("*[Authors and affiliation to be added.]*")
w("")
w("## Abstract")
w("")
w("### Background")
w("")
w("Continuous glucose monitors have historically reported at five-minute intervals, and sensors")
w("reporting every minute are now in routine use. It is generally assumed that the faster feed")
w("carries more information about glucose. Existing evidence bears on the question only")
w("indirectly, and the comparisons that have been published derive the slower signal by")
w("decimating a faster one, which conflates the behaviour of a slow sensor with that of a slowly")
w("read fast sensor.")
w("")
w("### Method")
w("")
w(f"One adult with type 1 diabetes wore a five-minute sensor for {P['e5']['n_days']} days")
w(f"({P['e5']['n']:,} readings) and subsequently a one-minute sensor for {P['e1']['n_days']} days")
w(f"({P['e1']['n']:,} readings). Both records were analysed as recorded, without decimation or")
w("interpolation. The principal instrument was the variogram, which is expressed in units of lag")
w("time and is therefore comparable across sampling rates, and which separates measurement noise")
w("from signal structure by construction. Forecasting and event prediction were modelled at each")
w("sensor's native rate with cross-validation grouped by day. Uncertainty was estimated by a")
w("block bootstrap over whole days.")
w("")
w("### Results")
w("")
w(f"The ratio of the two variograms was constant at {rs['mean']:.3f} across all lags observable by")
w(f"both sensors, from 5 to 120 minutes, with a total spread of {rs['spread_pct']:.1f}% of the mean and")
w("no systematic trend. Neither record exhibited a measurement-noise floor: at a one-minute lag")
w(f"the variogram was {V['vario']['e1']['1']['D']:.2f} mg/dl^2, which is")
w(f"{V['noise']['pct_of_lit_floor_at_1min']:.0f}% of the value that a published noise standard")
w("deviation of 3.19 mg/dl would impose at every lag. The log-log slope of the variogram was")
w(f"{s5['5-20']['slope']:.2f} (95% CI {s5['5-20']['lo']:.2f} to {s5['5-20']['hi']:.2f}) for the")
w(f"five-minute record and {s1['5-20']['slope']:.2f} ({s1['5-20']['lo']:.2f} to {s1['5-20']['hi']:.2f})")
w(f"for the one-minute record over 5 to 20 minutes. Below five minutes the slope was")
w(f"{s1['1-5']['slope']:.2f} ({s1['1-5']['lo']:.2f} to {s1['1-5']['hi']:.2f}), containing the value")
w("measured above it. Point-to-point acceleration was found to have no rate-independent value,")
w(f"differing by a factor of {sd_['measured_ratio']:.2f} between the two sensors, close to the")
w("factor predicted from the roughness of the signal. Normalised forecast error was")
w("indistinguishable between records at every horizon from 15 to 90 minutes. Prediction of")
w("hypoglycaemia and of hyperglycaemia was likewise indistinguishable once each record's own base")
w(f"rate was accounted for. Threshold crossings were reported {Dl['mean_difference']:.2f} minutes")
w("later by the five-minute sensor.")
w("")
w("### Conclusion")
w("")
w("The two sensors record the same process at the same relative noise, and their records differ")
w("by a single multiplicative constant attributable to glycaemic variability. One-minute sampling")
w("resolves no regime that five-minute sampling fails to imply and confers no measurable")
w("advantage in prediction. Its one demonstrable effect is a reduction of about two minutes in")
w("reporting latency, which is a scheduling property requiring no additional information.")
w("Acceleration computed from consecutive samples is a rate-dependent artefact and should not be")
w("used as a threshold quantity without reference to the interval it was computed over.")
w("")
w("## Introduction")
w("")
w("The five-minute reporting interval of continuous glucose monitors is an inheritance from the")
w("first commercially successful devices rather than a considered design choice, and it has")
w("propagated into the systems built upon them. Rate of change is customarily expressed per five")
w("minutes. Look-back windows are frequently specified as counts of samples. Closed-loop")
w("controllers almost universally act on a five-minute cycle.")
w("")
w("Sensors reporting at one-minute intervals are now widely worn, and the expectation attached to")
w("them is that a controller or an alarm will see further and sooner. Two distinct claims are")
w("usually conflated in that expectation. The first is informational: that a one-minute record")
w("resolves structure in glucose which a five-minute record does not. This is falsifiable by")
w("sampling theory, since a signal band-limited well below the slower Nyquist rate cannot contain")
w("such structure. The second is a claim about latency: that a system reading a faster feed learns")
w("of an event sooner. This is true by construction and requires no additional information.")
w("")
w("Earlier work bears on the first claim. Gough and colleagues characterised blood glucose")
w("directly and placed its band edge near 1 x 10^-3 Hz, recommending a sampling period of")
w("approximately 10 minutes.1 Breton and colleagues examined the interstitial compartment that a")
w("subcutaneous sensor actually measures, observed attenuation of fast variation relative to")
w("blood, and concluded that interstitial glucose can be characterised with an 18-minute sampling")
w("period.2 Fico and colleagues reported that 75% of spectral power in continuous monitor signals")
w("accumulates by a period of approximately 1.4 hours.3 Russon and colleagues approached the")
w("question from the opposite direction, coarsening five-minute records to fifteen minutes and")
w("finding distributional metrics unchanged while episode detection deteriorated.5")
w("")
w("What has not been reported, to our knowledge, is a direct comparison of records produced by")
w("sensors of differing rate on the same subject. The comparisons available derive the slower")
w("signal by discarding samples from a faster one. That procedure measures the loss incurred by")
w("reading a fast sensor slowly. It does not measure how a slow sensor differs from a fast one,")
w("because commercial devices filter internally before reporting and the filter is matched to the")
w("reporting rate. The present work addresses that gap.")
w("")
w("## Methods")
w("")
w("### The variogram")
w("")
w("The variogram, or structure function, of a signal x observed at time t is")
w("")
w("    D(tau) = E[ (x(t + tau) - x(t))^2 ]                                              (1)")
w("")
w("the expected squared change over a lag of tau minutes. It is suited to the present question")
w("for two reasons. It is parameterised by elapsed time rather than by sample index, so records")
w("of differing rate may be placed on a common axis without resampling either. It also separates")
w("measurement noise from signal by construction, as follows.")
w("")
w("### Separation of noise from signal")
w("")
w("Let the observed signal be the sum of a continuous process g and an independent measurement")
w("error of variance s^2. Each difference in equation (1) then contains two independent error")
w("draws, so")
w("")
w("    D(tau) = 2 s^2 + D_g(tau)                                                        (2)")
w("")
w("Because g is continuous, D_g(tau) tends to zero as tau tends to zero, whereas the noise term")
w("does not. Independent measurement error therefore appears as a floor beneath the variogram at")
w("every lag, including the shortest, and its height is twice the error variance. This floor is")
w("termed the nugget in the geostatistical literature. Its absence is informative: a record whose")
w("variogram descends smoothly to a small value at short lag cannot carry appreciable independent")
w("per-sample error.")
w("")
w("### Roughness and its consequences")
w("")
w("Over a range of lags the variogram of many natural signals is well described by a power law,")
w("")
w("    D(tau) = c tau^alpha                                                             (3)")
w("")
w("where alpha characterises the roughness of the signal. A value of 2 corresponds to a smooth")
w("differentiable process and a value of 0 to white noise. The exponent is estimated here as the")
w("slope of log D against log tau, which is invariant to the amplitude of the excursions and so")
w("permits records of differing glycaemic variability to be compared.")
w("")
w("The exponent governs the behaviour of finite differences. For any process the mean square of")
w("the second difference over an interval h satisfies the identity")
w("")
w("    E[ (x(t+h) - 2 x(t) + x(t-h))^2 ] = 4 D(h) - D(2h)                               (4)")
w("")
w("which under equation (3) becomes c h^alpha (4 - 2^alpha). Acceleration estimated from")
w("consecutive samples divides this by h^2, so its magnitude scales as")
w("")
w("    a(h) ~ h^(alpha/2 - 2)                                                           (5)")
w("")
w("Unless the underlying process is twice differentiable, in which case the leading term of")
w("equation (4) cancels and the next governs, acceleration estimated in this manner does not")
w("converge as the sampling interval is reduced. Its numerical value is then a property of the")
w("interval chosen rather than of the physiology.")
w("")
w("### Prediction")
w("")
w("Forecasting and event prediction were modelled at each record's native rate. Predictors")
w("comprised the current value together with backward differences over 5, 10, 15, 30 and 45")
w("minutes and ordinary least squares slopes over 15, 30 and 45 minutes. Both records were")
w("therefore afforded identical look-back in elapsed time, the faster record simply containing")
w("five times as many samples within each window. Validation used GroupKFold with whole days as")
w("groups, so that no day contributed to both training and test partitions.")
w("")
w("Forecast error is reported as root mean squared error divided by the standard deviation of the")
w("target, for which a value of unity denotes no improvement upon predicting the mean. Event")
w("prediction is reported as area under the receiver operating characteristic curve together with")
w("lift, defined as precision within the highest decile of predicted risk divided by the base")
w("rate of the record. Lift is the appropriate comparator here because the base rates of the two")
w("records differ substantially.")
w("")
w("### Reporting delay")
w("")
w("A threshold is crossed at an instant lying between two reported samples. The instant was")
w("located by linear interpolation between the bracketing samples and the delay measured to the")
w("next sample the sensor actually reported. No decimation was involved.")
w("")
w("### Uncertainty")
w("")
w("Glucose is strongly autocorrelated, so intervals computed over individual observations are")
w("inadmissibly narrow. All intervals reported are 95% block bootstraps resampling whole days")
w("with replacement.")
w("")
w("### Data")
w("")
w(f"One adult with type 1 diabetes wore a five-minute sensor from {P['e5']['start']} to")
w(f"{P['e5']['end']} and a one-minute sensor from {P['e1']['start']} to {P['e1']['end']}. The")
w(f"records comprise {P['e5']['n']:,} readings over {P['e5']['n_days']} days and {P['e1']['n']:,}")
w(f"readings over {P['e1']['n_days']} days respectively. Median inter-sample intervals were")
w(f"{P['e5']['median_gap']:.2f} and {P['e1']['median_gap']:.2f} minutes, with")
w(f"{P['e5']['pct_on_cadence']:.1f}% and {P['e1']['pct_on_cadence']:.1f}% of intervals within 30% of")
w("nominal.")
w("")
w("Glycaemic control differed between the two periods. Mean glucose was")
w(f"{P['e5']['mean']:.1f} mg/dl during the earlier period against {P['e1']['mean']:.1f} mg/dl during")
w(f"the later, with coefficients of variation of {P['e5']['cv']:.1f}% and {P['e1']['cv']:.1f}%. Time in")
w(f"the range 70 to 180 mg/dl was {P['e5']['tir']:.1f}% and {P['e1']['tir']:.1f}%. Time below 70 mg/dl")
w(f"was {P['e5']['tbr70']:.2f}% and {P['e1']['tbr70']:.2f}%, and time above 180 mg/dl")
w(f"{P['e5']['tar180']:.2f}% and {P['e1']['tar180']:.2f}%. The later period was thus the more")
w("volatile, by a factor of approximately")
w(f"{cp['cv_ratio_squared']:.2f} in variance. Glycaemic variability is a property of the subject and")
w("the period rather than of the sensor, and all comparisons below are consequently either")
w("scale-free or normalised by the base rate of the record concerned.")
w("")
w("## Results")
w("")
w("### Relationship between the two records")
w("")
w("Table 1 gives the variogram of each record at all lags observable by both sensors, together")
w("with their ratio.")
w("")
w("Table 1. Variograms and their ratio.")
w("")
w("| Lag (min) | Five-minute record (mg/dl^2) | One-minute record (mg/dl^2) | Ratio |")
w("|---|---|---|---|")
for r in V["ratio"]:
    a = V["vario"]["e5"][str(r["lag"])]; b = V["vario"]["e1"][str(r["lag"])]
    w(f"| {r['lag']} | {a['D']:.1f} ({a['lo']:.1f} to {a['hi']:.1f}) | "
      f"{b['D']:.1f} ({b['lo']:.1f} to {b['hi']:.1f}) | {r['ratio']:.3f} |")
w("")
w(f"The ratio averaged {rs['mean']:.3f} over a twenty-four-fold range of lag, with a total spread of")
w(f"{rs['spread_pct']:.1f}% of the mean. It exhibited no systematic trend, and in particular no")
w("departure at the shortest lags, which are the only lags at which the two sensors could differ.")
w("The records are therefore related by a single multiplicative constant. For comparison the")
w(f"squared ratio of coefficients of variation was {cp['cv_ratio_squared']:.3f}, so the majority of")
w("the constant is attributable to the change in glycaemic control between the periods.")
w("")
w("### Absence of a measurement-noise floor")
w("")
w(f"On the one-minute record the variogram fell to {V['vario']['e1']['1']['D']:.2f} mg/dl^2 at a")
w(f"one-minute lag ({V['vario']['e1']['1']['lo']:.2f} to {V['vario']['e1']['1']['hi']:.2f}) and showed")
w(f"no indication of levelling. Vettoretti and colleagues report a measurement noise standard")
w("deviation of 3.19 mg/dl for a factory-calibrated sensor,4 which by equation (2) would hold the")
w(f"variogram at {V['noise']['lit_floor']:.1f} mg/dl^2 at every lag. The observed value is")
w(f"{V['noise']['pct_of_lit_floor_at_1min']:.0f}% of that figure, and interpreted as white noise")
w(f"would correspond to a standard deviation of {V['noise']['implied_white_sd_at_1min']:.2f} mg/dl.")
w("")
w("Neither record therefore carries appreciable independent per-sample error. The values these")
w("devices report are not raw transducer output but the product of internal filtering, and it is")
w("that filtering rather than the reporting interval which determines the apparent smoothness of")
w("the series. The preceding section establishes the same point from the other direction, since")
w("there is no lag at which the faster record lies proportionally above the slower.")
w("")
w("### Roughness and the regime below five minutes")
w("")
w("Table 2 gives the log-log slope of the variogram by lag band.")
w("")
w("Table 2. Variogram exponent by record and lag band.")
w("")
w("| Record | Lag band (min) | Exponent alpha (95% CI) |")
w("|---|---|---|")
for k, lab in (("e5", "Five-minute"), ("e1", "One-minute")):
    for band, s in V["slopes"][k].items():
        if not isinstance(s, dict): continue
        w(f"| {lab} | {band.replace('-', ' to ')} | {s['slope']:.2f} ({s['lo']:.2f} to {s['hi']:.2f}) |")
w("")
w("In both bands observable by both sensors the exponents agree to two decimal places with")
w("overlapping intervals. Below five minutes, a region accessible only to the faster sensor, the")
w(f"exponent was {s1['1-5']['slope']:.2f} ({s1['1-5']['lo']:.2f} to {s1['1-5']['hi']:.2f}), an interval")
w(f"containing the {s1['5-20']['slope']:.2f} observed immediately above. The same power law thus")
w("extends from one minute to sixty without discontinuity. The additional samples describe the")
w("existing curve more finely rather than revealing a further regime.")
w("")
w("An exponent near 1.3 places the signal well away from either limiting case. It is not a smooth")
w("differentiable process, for which the exponent would approach 2, and it is far from white")
w("noise, for which the exponent would be 0.")
w("")
w("### Point-to-point acceleration")
w("")
w(f"On the five-minute record the second difference over one interval had a standard deviation of")
w(f"{Ac['e5']['sd_raw_mgdl']:.2f} mg/dl, against {Ac['e5']['variogram_pred_sd_raw']:.2f} mg/dl")
w("predicted by equation (4) from the variogram with no free parameters. Acceleration therefore")
w("conveys nothing that the variogram has not already described.")
w("")
w("Expressed as mg/dl per 5 min per 5 min so that the two records may be compared, the standard")
w(f"deviation was {Ac['e5']['sd_per5per5']:.2f} on the five-minute record and")
w(f"{Ac['e1']['sd_per5per5']:.2f} on the one-minute record, a ratio of {sd_['measured_ratio']:.2f}.")
w(f"Equation (5) predicts {sd_['by_alpha']['this record, 1 to 5 min']['predicted_ratio']:.2f} from the")
w(f"sub-five-minute exponent of {sd_['by_alpha']['this record, 1 to 5 min']['alpha']:.2f} measured on")
w("this record. A twice differentiable signal would give unity, since acceleration would converge")
w("upon a fixed value as the interval was reduced. It does not converge here. The quantity has no")
w("rate-independent value, and a threshold placed upon it is a threshold at one particular")
w("sampling rate.")
w("")
w("The lag-one autocorrelation of the acceleration series was")
w(f"{Ac['e5']['acf1']:+.3f} on the five-minute record and {Ac['e1']['acf1']:+.3f} on the one-minute")
w("record, against a value of -0.667 for twice-differenced white noise. The one-minute series is")
w("accordingly smooth rather than noisy, which follows from the absence of a nugget reported")
w("above and does not by itself imply that the quantity is informative.")
w("")
w("Table 3 addresses that last point directly, giving prediction within 30 minutes with and")
w("without acceleration among the predictors.")
w("")
w("Table 3. Event prediction with and without acceleration.")
w("")
w("| Record | Event | Predictors | AUC (95% CI) | Lift |")
w("|---|---|---|---|---|")
for k, lab in (("e5", "Five-minute"), ("e1", "One-minute")):
    for task, rows in Ac["predictive_value"][k].items():
        for sname, r in rows.items():
            w(f"| {lab} | {task.replace('<', 'below ').replace('>', 'above ')} | {sname} | "
              f"{r['auc']:.4f} ({r['lo']:.4f} to {r['hi']:.4f}) | {r['lift']:.2f} |")
w("")
w("Every variant lies within a few thousandths of the velocity-only baseline with overlapping")
w("intervals. Neither the point-to-point form nor the overlapping-window form conveys predictive")
w("information beyond that already carried by the velocity terms, at either sampling rate.")
w("")
w("### Forecasting")
w("")
w("Table 4. Normalised forecast error by horizon.")
w("")
w("| Horizon (min) | Five-minute record | One-minute record | Intervals |")
w("|---|---|---|---|")
for H, cm in F["comparison"].items():
    a = F["e5"]["horizons"][H]; b = F["e1"]["horizons"][H]
    w(f"| {H} | {a['model']:.3f} ({a['model_lo']:.3f} to {a['model_hi']:.3f}) | "
      f"{b['model']:.3f} ({b['model_lo']:.3f} to {b['model_hi']:.3f}) | "
      f"{'overlapping' if cm['overlap'] else 'separated'} |")
w("")
w("Intervals overlap at every horizon examined and the nominally superior record alternates")
w("between horizons. No forecast advantage is detectable in either direction.")
w("")
w("### Prediction of hypoglycaemia and hyperglycaemia")
w("")
w("Table 5. Event prediction by horizon.")
w("")
w("| Event | Horizon (min) | Record | Base rate | AUC (95% CI) | Lift (95% CI) |")
w("|---|---|---|---|---|---|")
for task in ["low <70", "low <54", "high >180", "high >250"]:
    for H in ["15","20","30","45","60"]:
        row = Ev["tasks"][task].get(H)
        if not row: continue
        for k, lab in (("e5", "5-min"), ("e1", "1-min")):
            r = row.get(k)
            if not r: continue
            nm = task.replace("low <", "below ").replace("high >", "above ")
            if r.get("too_rare"):
                w(f"| {nm} | {H} | {lab} | {100*r['base']:.2f}% | not modelled | |")
            else:
                w(f"| {nm} | {H} | {lab} | {100*r['base']:.2f}% | "
                  f"{r['auc']:.4f} ({r['auc_lo']:.4f} to {r['auc_hi']:.4f}) | "
                  f"{r['lift']:.2f} ({r['lift_lo']:.2f} to {r['lift_hi']:.2f}) |")
w("")
w("On lift, which is free of the base rate, the two records are indistinguishable throughout. The")
w("area under the curve is nominally higher for the one-minute record in the prediction of")
w("hypoglycaemia and nominally lower in the prediction of hyperglycaemia, the deficit in the")
w("latter widening with horizon. A property of the sampling interval cannot assist prediction in")
w("one direction while impeding it in the other. A genuine advantage of rate would moreover be")
w("greatest at the shortest horizon, where recent detail is most informative, and would diminish")
w("as the horizon lengthened. Neither event behaves in that manner. The differences track the")
w("difficulty of the respective periods.")
w("")
w("### Meal climbs")
w("")
w("Climbs were defined as a rise of at least 40 mg/dl from a local trough within 90 minutes.")
w(f"The five-minute record contained {Mc['e5']['n_climbs']} such episodes")
w(f"({Mc['e5']['per_day']:.2f} per day, median rise {Mc['e5']['median_rise']:.0f} mg/dl, median")
w(f"time to peak {Mc['e5']['median_duration']:.0f} minutes) and the one-minute record")
w(f"{Mc['e1']['n_climbs']} ({Mc['e1']['per_day']:.2f} per day, {Mc['e1']['median_rise']:.0f} mg/dl,")
w(f"{Mc['e1']['median_duration']:.0f} minutes).")
w("")
w("Two tasks were posed. The first asks, from a state in which glucose is not currently rising,")
w("whether a climb will begin within the next H minutes. This is anticipation proper, since the")
w("model must fire before the rise is visible. The second asks, once a climb is under way,")
w("whether it will peak within the next H minutes. Both models were trained only on this")
w("subject's own data and are therefore personalised in the fullest sense available.")
w("")
w("Table 6. Prediction of climb onset and of climb peak.")
w("")
w("| Task | Horizon (min) | Record | Base rate | AUC (95% CI) | Lift |")
w("|---|---|---|---|---|---|")
for kind, nm in (("onset", "onset"), ("end", "peak")):
    for H in ["10","15","20","30"]:
        for k, lab in (("e5", "5-min"), ("e1", "1-min")):
            r = Mc[k][kind].get(H)
            if not r: continue
            w(f"| {nm} | {H} | {lab} | {100*r['base']:.2f}% | "
              f"{r['auc']:.4f} ({r['lo']:.4f} to {r['hi']:.4f}) | {r['lift']:.2f} |")
w("")
w("Onset carries a modest but genuine signal at both rates, with areas under the curve between")
w("0.61 and 0.67 against 0.5 for chance. It is not a strong signal. At the ten-minute horizon on")
w("the five-minute record the highest decile of predicted risk contains 2.42 times the base rate")
w("of 2.98%, which is a precision of approximately 7%.")
w("")
w("The approach of the peak is considerably more predictable, with areas under the curve near")
w("0.88 to 0.90 at the ten-minute horizon. This is unsurprising, since the flattening that")
w("precedes a peak is directly observable in the rate of change.")
w("")
w("For neither task did the faster record perform better. The difference in area under the curve")
w("favoured the five-minute record at every horizon of both tasks, by between 0.016 and 0.040,")
w("with overlapping intervals throughout. Sampling rate is not the constraint on anticipation.")
w("")
w("### Reporting delay")
w("")
w("Table 7. Delay from threshold crossing to the next reported sample.")
w("")
w("| Crossing | Five-minute record | One-minute record | Difference |")
w("|---|---|---|---|")
labels = {"70.0": "below 70 mg/dl", "54.0": "below 54 mg/dl",
          "180.0": "above 180 mg/dl", "250.0": "above 250 mg/dl"}
def cell(d):
    return "too few crossings" if d.get("too_few") else \
           f"{d['mean']:.2f} min ({d['mean_lo']:.2f} to {d['mean_hi']:.2f}), n = {d['n']}"
for thr, lab in labels.items():
    a = Dl["e5"]["thresholds"].get(thr); b = Dl["e1"]["thresholds"].get(thr)
    if not a or not b: continue
    diff = "" if (a.get("too_few") or b.get("too_few")) else f"{a['mean']-b['mean']:.2f} min"
    w(f"| {lab} | {cell(a)} | {cell(b)} | {diff} |")
w("")
w(f"The mean difference was {Dl['mean_difference']:.2f} minutes against an arithmetic expectation of")
w("2.00 minutes from the sample spacing alone.")
w("")
w("## Discussion")
w("")
w("Two sensors of differing rate worn consecutively by the same subject produced records related")
w("by a single multiplicative constant across every lag they had in common. Neither carried a")
w("measurable noise floor. The faster sensor resolved no regime below the sampling limit of the")
w("slower one, forecast no better at any horizon examined, and predicted neither hypoglycaemia")
w("nor hyperglycaemia better once base rates were accounted for.")
w("")
w("These observations are consistent with the earlier literature and supply a direct test of it.")
w("Gough and colleagues placed the band edge of blood glucose near a seventeen-minute period.1")
w("Breton and colleagues attributed the further attenuation observed in the interstitium to")
w("diffusion between the compartments acting as a low-pass filter, and estimated that interstitial")
w("glucose is fully characterised by an eighteen-minute sampling period.2 A filter of that kind")
w("lies upstream of both devices examined here and is a property of physiology rather than of")
w("electronics. Sampling faster cannot recover content that diffusion has already removed, which")
w("is the mechanism underlying the constancy of the ratio in Table 1.")
w("")
w("The absence of a nugget merits comment, since published error models attribute a noise standard")
w("deviation of approximately 3 mg/dl to these devices.4 Those models describe the raw transducer")
w("signal. What reaches the user has been filtered, and the present data indicate that the")
w("filtering removes the greater part of the error the models describe. A practical consequence")
w("is that the apparent cleanliness of a continuous glucose record is set by the manufacturer's")
w("processing rather than by its reporting rate.")
w("")
w("The acceleration result has a bearing on system design. Quantities computed as second")
w("differences of consecutive samples are widely used as inputs to control algorithms and to")
w("alarm logic. Equation (5) establishes that such a quantity has no rate-independent value")
w("unless the underlying signal is twice differentiable, and the exponent measured here places")
w("interstitial glucose firmly outside that class. A threshold calibrated on five-minute data")
w(f"will be encountered approximately {sd_['measured_ratio']:.1f} times as often, in standardised")
w("units, when the same logic is presented with one-minute data. Constructions that average rates")
w("over windows fixed in elapsed time rather than in samples do not suffer this defect.")
w("")
w("The one effect attributable to sampling rate was a reduction of approximately two minutes in")
w("the delay between a threshold being crossed and its being reported, a figure matching the")
w("arithmetic expectation from sample spacing. This is a scheduling property and requires no")
w("additional information about glucose. Its practical value depends upon what consumes it. An")
w("alarm can exploit it in full, as can a subject able to respond immediately. It is small in")
w("relation to the onset of rapid-acting insulin, which is of the order of fifteen minutes.")
w("")
w("Several limitations attach to this work. It concerns a single subject, and the comparison is")
w("observational and between periods, so that sensor hardware and glycaemic control both changed")
w("at the boundary. The analysis was designed with that in view, every measure employed being")
w("either scale-free or normalised by base rate, but a single subject cannot establish")
w("generalisation across devices or across people. The makes and models of the sensors were not")
w("recorded in the data available. The conclusion regarding noise concerns the reported series")
w("rather than the transducer signal beneath it. Certain events proved too infrequent to model in")
w("one record or the other and are marked accordingly. No outcome data were analysed, none being")
w("required for the question posed.")
w("")
w("The comparison would be strengthened by replication across subjects and across manufacturers,")
w("and by a design in which two sensors of differing rate are worn concurrently, which would")
w("remove the confounding of period with device that is unavoidable in a consecutive design.")
w("")
w("## Abbreviations")
w("")
w("AUC, area under the receiver operating characteristic curve; BG, blood glucose; CGM,")
w("continuous glucose monitor; CI, confidence interval; CV, coefficient of variation; IG,")
w("interstitial glucose; RMSE, root mean squared error; SD, standard deviation; T1DM, type 1")
w("diabetes mellitus.")
w("")
w("## References")
w("")
w("1. Gough DA, Kreutz-Delgado K, Bremer TM. Frequency characterization of blood glucose")
w("dynamics. Ann Biomed Eng. 2003;31(1):91-97.")
w("")
w("2. Breton MD, Shields DP, Kovatchev BP. Optimum subcutaneous glucose sampling and Fourier")
w("analysis of continuous glucose monitors. J Diabetes Sci Technol. 2008;2(3):495-500.")
w("")
w("3. Fico G, Hernanz L, Cancela J, et al. Exploring the frequency domain of continuous glucose")
w("monitoring signals to improve characterization of glucose variability and of diabetic")
w("profiles. J Diabetes Sci Technol. 2017;11(4):773-779.")
w("")
w("4. Vettoretti M, Battocchio C, Sparacino G, Facchinetti A. Development of an error model for a")
w("factory-calibrated continuous glucose monitoring sensor with 10-day lifetime. Sensors (Basel).")
w("2019;19(23):5320.")
w("")
w("5. Russon CL, Pulsford RM, Allen MJ, et al. Impact of recording interval in continuous glucose")
w("monitoring on calculating the metrics of glycemic control. J Diabetes Sci Technol.")
w("2025;19(2):590-592.")
w("")
w("## Appendix: reproduction")
w("")
w("```")
w("./run_all.sh")
w("")
w("01_profile.py          coverage, sampling stability, glycaemic distribution")
w("02_variogram.py        variogram ratio, noise floor, exponents")
w("03_forecast.py         normalised forecast error by horizon")
w("04_events.py           event prediction, AUC and lift")
w("05_reporting_delay.py  delay from an interpolated crossing to the next reported sample")
w("06_acceleration.py     point-to-point acceleration, scale dependence, predictive value")
w("07_meal_climbs.py      prediction of climb onset and of climb peak")
w("08_report.py           regenerates this document from results/*.json")
w("09_style_check.py      house-style gate on the generated document")
w("```")
w("")
w("Every figure in this document is read from the stored results. None is transcribed by hand.")

def rewrap(lines, width=92):
    res, buf, in_code = [], [], False
    def flush():
        if buf:
            res.extend(textwrap.wrap(" ".join(buf), width=width,
                                     break_long_words=False, break_on_hyphens=False))
            buf.clear()
    for l in lines:
        if l.strip().startswith("```"):
            flush(); in_code = not in_code; res.append(l); continue
        if in_code or not l.strip() or l.strip().startswith(("|", "#", "-", "*")) \
           or l.startswith("    "):
            flush(); res.append(l); continue
        buf.append(l.strip())
    flush()
    return res

dest = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                     "..", "..", "reports", "2026-07_cgm_cadence_report.md"))
with open(dest, "w") as f: f.write("\n".join(rewrap(out)) + "\n")
print(f"report written: {dest} ({len(out)} lines)")
